server:
    port: 8085
spring:
  jackson:
    date-format: "dd.MM.yyyy"
  datasource:
    url: jdbc:mysql://localhost:3306/coaching_center
    username: root
    password: "#MySQL2023"
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
